# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 782)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.table1 = QtWidgets.QTableWidget(self.centralwidget)
        self.table1.setObjectName("table1")
        self.table1.setColumnCount(8)
        self.table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(7, item)
        self.verticalLayout.addWidget(self.table1)
        self.table2 = QtWidgets.QTableWidget(self.centralwidget)
        self.table2.setObjectName("table2")
        self.table2.setColumnCount(8)
        self.table2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(7, item)
        self.verticalLayout.addWidget(self.table2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HuoBi Monitor"))
        item = self.table1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "交易对"))
        item = self.table1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1hour"))
        item = self.table1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "30min"))
        item = self.table1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "15min"))
        item = self.table1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5min"))
        item = self.table1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "买入价"))
        item = self.table1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "止损警示"))
        item = self.table1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "锁定"))
        item = self.table2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "交易对"))
        item = self.table2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1hour"))
        item = self.table2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "30min"))
        item = self.table2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "15min"))
        item = self.table2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5min"))
        item = self.table2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "买入价"))
        item = self.table2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "止损警示"))
        item = self.table2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "锁定"))


